import { describe, expect, it } from 'vitest';
import { combatStats, createV2State, makeV2Hero, resolveV2Round } from './model';
describe('isolated combat v2 model',()=>{
  it('keeps peer Heroes alive for multiple simultaneous clashes',()=>{let s=createV2State(7,['kng-common-knight'],['und-bone-soldier']);s=resolveV2Round(s,[{cardId:'kng-common-knight',lane:'center'}],[{cardId:'und-bone-soldier',lane:'center'}]);expect(s.player.heroes.center?.hp).toBeGreaterThan(0);expect(s.enemy.heroes.center?.hp).toBeGreaterThan(0);expect(s.events.filter(e=>e.type==='HERO_DAMAGE')).toHaveLength(2);});
  it('persists damage and destroys Heroes at zero HP',()=>{let s=createV2State(3,['kng-common-knight'],['und-bone-soldier']);s.player.heroes.center=makeV2Hero('kng-common-knight');s.enemy.heroes.center=makeV2Hero('und-bone-soldier');s.enemy.heroes.center.hp=1;s=resolveV2Round(s,[],[]);expect(s.enemy.heroes.center).toBeUndefined();expect(s.enemy.defeated).toContain('und-bone-soldier');expect(s.player.heroes.center?.hp).toBeLessThan(s.player.heroes.center?.maxHp??999);});
  it('deals reduced direct lane damage and resolves translated heal and shield spells',()=>{let s=createV2State(3,['kng-common-knight'],['und-bone-soldier']);s.player.heroes.left=makeV2Hero('kng-common-knight');const attack=s.player.heroes.left.attack;const before=s.enemy.commanderHp;s=resolveV2Round(s,[],[]);expect(before-s.enemy.commanderHp).toBe(Math.ceil(attack*.75));s.player.heroes.center=makeV2Hero('kng-common-knight');s.player.heroes.center.hp=5;s=resolveV2Round(s,[{cardId:'spl-second-chance',lane:'center',spell:'heal'},{cardId:'spl-aegis-ward',lane:'center',spell:'shield'}],[]);expect(s.player.heroes.center?.hp).toBe(17);expect(s.player.heroes.center?.shield).toBe(10);});
  it('translates selected existing damage, attack buff/debuff, and shield spells',()=>{expect(resolveV2Round(createV2State(1,['kng-common-knight'],['und-bone-soldier']),[{cardId:'kng-common-knight',lane:'center'},{cardId:'spl-power-surge',lane:'center',spell:'attackUp'}],[{cardId:'und-bone-soldier',lane:'center'},{cardId:'spl-weakness',lane:'center',spell:'attackDown'}]).events.some(event=>event.type==='HERO_BUFF')).toBe(true);});
  it('scales Level and Ascension in bounded, readable steps',()=>{const base=combatStats('kng-common-knight',1,0),high=combatStats('kng-common-knight',60,2);expect(high.attack-base.attack).toBe(9);expect(high.maxHp-base.maxHp).toBe(47);expect(combatStats('kng-common-knight',20,0).attack).toBeGreaterThan(base.attack);});
  it('uses deterministic event output and supports boss scale',()=>{const run=()=>resolveV2Round(createV2State(4,['kng-common-knight'],['und-vharos'],{boss:true}),[{cardId:'kng-common-knight',lane:'left'}],[]);expect(run()).toEqual(run());expect(createV2State(4,['kng-common-knight'],['und-vharos'],{boss:true}).enemy.commanderHp).toBe(600);});
  it('consumes each deck Hero once and leaves exhausted lanes empty',()=>{let s=createV2State(4,['kng-common-knight'],['und-bone-soldier']);s=resolveV2Round(s,[{cardId:'kng-common-knight',lane:'left'}],[{cardId:'und-bone-soldier',lane:'right'}]);expect(s.player.cardsLeft).toEqual([]);expect(s.enemy.cardsLeft).toEqual([]);s=resolveV2Round(s,[{cardId:'kng-common-knight',lane:'center'}],[{cardId:'und-bone-soldier',lane:'center'}]);expect(s.player.heroes.center).toBeUndefined();expect(s.enemy.heroes.center).toBeUndefined();expect(s.player.deployed).toEqual(['kng-common-knight']);});
});
