import type { CampaignChapterDef } from './types';

// Region 1 / Chapter 1 - "The Ashen Road". The one real, playable chapter of this vertical slice (see
// types.ts). Thirteen nodes: an intro story beat, six standard battles, one optional challenge spur,
// one story beat, one elite, one boss and two reward claims - matching the design's own "teaches one
// mechanic per node" progression (placement, spells, continuous spells, overflow, conditional
// effects, graveyard synergy, then the boss combines them).
//
// encounterDecks.ts supplies a distinct legal deck for each tactical lesson. Only the boss uses the
// full Undead starter. Vharos is in its deck; drawing him is subject to normal shuffle/draw rules.

const UNDEAD_ENCOUNTER = (overrides: Partial<import('./types').CampaignEncounterDef> & Pick<import('./types').CampaignEncounterDef, 'foeName' | 'foeCardId' | 'threat' | 'energyCost' | 'objectives' | 'firstClearReward' | 'repeatReward'>): import('./types').CampaignEncounterDef => ({
  foeFaction: 'undead',
  enemyDeckFaction: 'undead',
  ...overrides,
});

export const CHAPTER_1: CampaignChapterDef = {
  id: 'chapter-1',
  regionId: 'region-1',
  name: 'Watch on the dust road',
  meta: 'Region 1 · Chapter 1',
  nodes: [
    {
      id: 'story-road-home',
      type: 'story',
      name: 'The road home',
      teach: 'Placement',
      x: 26,
      y: 566,
      requires: [],
      story: {
        speakerName: 'You',
        speakerFaction: 'kingdom',
        speakerRole: 'Watch captain',
        lines: ['The ash started falling three days ago. It hasn’t stopped since.', 'Something is walking out of the barrows below the old watchtower. Time to find out what.'],
      },
    },
    {
      id: 'battle-broken-palisade',
      type: 'battle',
      name: 'Broken Palisade',
      teach: 'Hero placement',
      x: 118,
      y: 592,
      requires: ['story-road-home'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Cursed Warrior band',
        foeCardId: 'und-bone-soldier',
        threat: 1,
        energyCost: 5,
        recommendedRosterPower: 400,
        objectives: [],
        firstClearReward: { label: 'Bone Soldier', sub: 'Three Undead recruits join your road', icon: 'card', cardId: 'und-bone-soldier', count: 3 },
        repeatReward: { label: '1 ember', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'battle-dust-crossing',
      type: 'battle',
      name: 'Dust Crossing',
      teach: 'Spells',
      x: 214,
      y: 540,
      requires: ['battle-broken-palisade'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Bone Soldier warband',
        foeCardId: 'und-bone-soldier',
        threat: 2,
        energyCost: 5,
        recommendedRosterPower: 450,
        objectives: [
          { id: 'rounds', text: 'Win within 5 rounds', check: 'roundsWithin', value: 5 },
          { id: 'hp', text: 'Take less than 8 damage', check: 'healthAtLeast', value: 12 },
        ],
        firstClearReward: { label: 'Second Chance', sub: 'Your first Undead spells', icon: 'card', cardId: 'spl-second-chance', count: 2 },
        repeatReward: { label: '2 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'reward-wayside-cairn',
      type: 'reward',
      name: 'Wayside cairn',
      teach: 'Reward',
      x: 292,
      y: 588,
      requires: ['battle-dust-crossing'],
      reward: { label: 'Raise Fallen', sub: 'A cairn left by an earlier traveller', icon: 'card', cardId: 'spl-raise-fallen', count: 2 },
    },
    {
      id: 'battle-ford-of-ash',
      type: 'battle',
      name: 'Ford of Ash',
      teach: 'Continuous spells',
      x: 374,
      y: 530,
      requires: ['reward-wayside-cairn'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Bone Soldier warband',
        foeCardId: 'und-bone-soldier',
        threat: 2,
        energyCost: 5,
        recommendedRosterPower: 500,
        objectives: [
          { id: 'rounds', text: 'Win within 5 rounds', check: 'roundsWithin', value: 5 },
          { id: 'hp', text: 'Take less than 8 damage', check: 'healthAtLeast', value: 12 },
        ],
        firstClearReward: { label: 'Grave Totem', sub: 'A Continuous spell for the long road', icon: 'card', cardId: 'spl-grave-totem' },
        repeatReward: { label: '2 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'challenge-toll-of-the-ford',
      type: 'challenge',
      name: 'Toll of the Ford',
      teach: 'Optional',
      x: 410,
      y: 624,
      requires: ['battle-ford-of-ash'],
      optional: true,
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Cursed Warrior band',
        foeCardId: 'und-bone-soldier',
        threat: 3,
        energyCost: 5,
        startingHp: 12,
        recommendedRosterPower: 550,
        modifier: { title: 'Challenge rule', text: 'You start at 12 health instead of 20.' },
        objectives: [
          { id: 'hp', text: 'Never fall below 5 health', check: 'healthAtLeast', value: 5 },
          { id: 'faction', text: 'Win with a Kingdom deck', check: 'deckFactionKingdom' },
        ],
        firstClearReward: { label: 'Royal Guard', sub: 'Won with Kingdom steel - a spare Guard for Ascension', icon: 'card', cardId: 'kng-royal-guard' },
        repeatReward: { label: '1 ember', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'battle-grey-orchard',
      type: 'battle',
      name: 'Grey Orchard',
      teach: 'Overflow damage',
      x: 490,
      y: 566,
      requires: ['battle-ford-of-ash'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Bone Soldier warband',
        foeCardId: 'und-bone-soldier',
        threat: 3,
        energyCost: 5,
        recommendedRosterPower: 550,
        objectives: [
          { id: 'rounds', text: 'Win within 6 rounds', check: 'roundsWithin', value: 6 },
          { id: 'overflow', text: 'Deal 5+ overflow damage', check: 'overflowDealtAtLeast', value: 5 },
        ],
        firstClearReward: { label: 'Cursed Warrior', sub: 'Two more blades for the barrows', icon: 'card', cardId: 'und-cursed-warrior', count: 2 },
        repeatReward: { label: '2 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'story-what-the-ash-carries',
      type: 'story',
      name: 'What the ash carries',
      teach: 'Story',
      x: 562,
      y: 524,
      requires: ['battle-grey-orchard'],
      story: {
        speakerName: 'Mira',
        speakerFaction: 'undead',
        speakerRole: 'Grave Warden',
        lines: ['The ash is not from a fire. It is what is left when something walks out of a grave and keeps walking.', 'Hold the ford. I will see what waits at the barrow.'],
      },
    },
    {
      id: 'battle-chapel-of-dust',
      type: 'battle',
      name: 'Chapel of Dust',
      teach: 'Conditional effects',
      x: 642,
      y: 558,
      requires: ['story-what-the-ash-carries'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Dark Priest coven',
        foeCardId: 'und-bone-soldier',
        threat: 3,
        energyCost: 5,
        recommendedRosterPower: 600,
        objectives: [
          { id: 'rounds', text: 'Win within 6 rounds', check: 'roundsWithin', value: 6 },
          { id: 'hp', text: 'Take less than 10 damage', check: 'healthAtLeast', value: 10 },
        ],
        firstClearReward: { label: 'Dark Priest', sub: 'Two Dark Priests answer the call', icon: 'card', cardId: 'und-dark-priest', count: 2 },
        repeatReward: { label: '2 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'elite-mira-grave-warden',
      type: 'elite',
      name: 'Mira, Grave Warden',
      teach: 'Graveyard synergy',
      x: 730,
      y: 516,
      requires: ['battle-chapel-of-dust'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Mira',
        foeCardId: 'und-mira',
        threat: 4,
        energyCost: 7,
        recommendedRosterPower: 650,
        modifier: { title: 'Encounter rule', text: 'Mira’s warband leans hard on the graveyard - expect returned and revived Heroes all match.' },
        objectives: [
          { id: 'nohero', text: 'Win without losing a Hero', check: 'noHeroLost' },
          { id: 'overflow', text: 'Deal 10+ overflow damage', check: 'overflowDealtAtLeast', value: 10 },
        ],
        firstClearReward: { label: 'Mira', sub: 'The Grave Warden changes sides', icon: 'card', cardId: 'und-mira', count: 2 },
        repeatReward: { label: '3 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'battle-barrow-steps',
      type: 'battle',
      name: 'Barrow Steps',
      teach: 'Archetype synergy',
      x: 814,
      y: 542,
      requires: ['elite-mira-grave-warden'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Grave Knight vanguard',
        foeCardId: 'und-bone-soldier',
        threat: 4,
        energyCost: 5,
        recommendedRosterPower: 700,
        objectives: [
          { id: 'rounds', text: 'Win within 6 rounds', check: 'roundsWithin', value: 6 },
          { id: 'hp', text: 'Take less than 10 damage', check: 'healthAtLeast', value: 10 },
        ],
        firstClearReward: { label: 'Grave Knight', sub: 'Three Grave Knights ride out', icon: 'card', cardId: 'und-grave-knight', count: 3 },
        repeatReward: { label: '2 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'boss-grave-tyrant',
      type: 'boss',
      name: 'Grave Tyrant',
      teach: 'Combines all six',
      x: 910,
      y: 498,
      requires: ['battle-barrow-steps'],
      encounter: UNDEAD_ENCOUNTER({
        foeName: 'Vharos, the Grave Tyrant',
        foeCardId: 'und-vharos',
        threat: 5,
        energyCost: 10,
        // The visible progression wall (docs/COMMERCIAL-PROTOTYPE-PLAN.md Phase 3): comfortably above what
        // pure card collection alone yields (~575-765 across the whole 1-20 account range with no
        // deliberate Level/Ascension spend, measured directly from rosterPowerForDeck - see the "diag"
        // note in campaign/powerCurve.test.ts). A few Hero Levels or the free Ascension from the Toll of
        // the Ford challenge close the gap; strategy still decides the fight itself.
        recommendedRosterPower: 800,
        modifier: { title: 'Encounter rule', text: 'The full Undead starter deck, Vharos included - every mechanic Chapter 1 taught, at once.' },
        objectives: [
          { id: 'rounds', text: 'Win within 8 rounds', check: 'roundsWithin', value: 8 },
          { id: 'hp', text: 'Keep 10 or more health', check: 'healthAtLeast', value: 10 },
        ],
        firstClearReward: { label: 'Vharos', sub: 'Legendary + chapter seal', icon: 'card', cardId: 'und-vharos' },
        repeatReward: { label: '5 embers', sub: 'Every clear after the first', icon: 'ember' },
      }),
    },
    {
      id: 'reward-chapter-seal',
      type: 'reward',
      name: 'Chapter seal',
      teach: 'Chapter reward',
      x: 1000,
      y: 480,
      requires: ['boss-grave-tyrant'],
      reward: { label: 'Chapter seal', sub: 'Watch on the dust road, held', icon: 'emblem' },
      completesChapter: true,
    },
  ],
};
