import { useRef, useState } from 'react';
import { Icon } from '../components/Icon';
import { getCard } from '../game/cards';
import { getActiveDeck } from '../game/engine/activeDeck';
import { STARTER_DECKS } from '../game/cards/starterDecks';
import { createV2State, resolveV2Round, translatePrototypeSpell, type V2Play, type V2State } from '../game/combatV2/model';
import { track } from '../analytics/track';
import { heroLevelsFor } from '../game/heroLevel/store';
import { ascensionRanksFor } from '../game/ascension/store';
import '../styles/combatV2.css';

type Mode='normal'|'campaign'|'boss';
const modes: {id:Mode;name:string;detail:string}[]=[{id:'normal',name:'AI Trial',detail:'Standard rival formation'},{id:'campaign',name:'Campaign Trial',detail:'Same prototype rules, no Campaign rewards'},{id:'boss',name:'Boss Trial',detail:'600 HP commander with a centre-lane guardian'}];
export function CombatV2LabPage({onBack}:{onBack:()=>void}) {
 const deck=getActiveDeck();const playerPool=deck.cardIds.filter(id=>getCard(id).type==='hero');const enemyPool=STARTER_DECKS.undead.filter(id=>getCard(id).type==='hero');const playerLevels=heroLevelsFor(playerPool);const playerAscensions=ascensionRanksFor(playerPool);const uniquePlayerHeroes=[...new Set(playerPool)];const aiLevel=uniquePlayerHeroes.length?Math.round(uniquePlayerHeroes.reduce((sum,id)=>sum+(playerLevels[id]??1),0)/uniquePlayerHeroes.length):1;const aiLevels=Object.fromEntries([...new Set(enemyPool)].map(id=>[id,aiLevel]));
 const [mode,setMode]=useState<Mode>('normal');const [state,setState]=useState<V2State|null>(null);const [choices,setChoices]=useState<Record<string,string>>({left:playerPool[0]??'',center:playerPool[1]??'',right:playerPool[2]??''});const [spell,setSpell]=useState<'fireball'|'attackUp'|'attackDown'|'shield'>('fireball');const startedAt=useRef(0);
 function start(){const next=createV2State(0x4d4f4f+Date.now()%10000,playerPool,enemyPool,{boss:mode==='boss',playerLevels,playerAscensions,enemyLevel:aiLevel,enemyLevels:aiLevels});setState(next);startedAt.current=Date.now();track('combat_model_used',{model:'v2',mode});}
 function resolve(){if(!state||state.status!=='IN_PROGRESS')return;const playerPlays:V2Play[]=[];const playerRemaining=[...state.player.cardsLeft];for(const lane of ['left','center','right'] as const){if(state.player.heroes[lane])continue;const chosen=choices[lane];const cardId=chosen&&playerRemaining.includes(chosen)?chosen:playerRemaining[0];if(cardId){playerPlays.push({cardId,lane,level:playerLevels[cardId]??1,ascension:playerAscensions[cardId]??0});playerRemaining.splice(playerRemaining.indexOf(cardId),1);}}
  const spellCard=spell==='fireball'?'spl-fireball':spell==='attackUp'?'spl-power-surge':spell==='attackDown'?'spl-weakness':'spl-aegis-ward';const translated=translatePrototypeSpell(spellCard);if(translated)playerPlays.push({cardId:spellCard,lane:'center',spell:translated});
  const enemyPlays:V2Play[]=[];const enemyRemaining=[...state.enemy.cardsLeft];for(const lane of ['left','center','right'] as const){if(state.enemy.heroes[lane])continue;if(mode==='boss'&&lane==='center'&&state.enemy.deployed.includes('und-vharos'))continue;const bossGuard=mode==='boss'&&lane==='center'&&enemyRemaining.includes('und-vharos');const cardId=bossGuard?'und-vharos':enemyRemaining[0];if(cardId){enemyPlays.push({cardId,lane,level:aiLevels[cardId]??1});enemyRemaining.splice(enemyRemaining.indexOf(cardId),1);}}
  const next=resolveV2Round(state,playerPlays,enemyPlays);setState(next);if(next.status!=='IN_PROGRESS'){const all=next.events;track('battle_round_count',{model:'v2',mode,rounds:next.round-1});track('hero_damage_total',{model:'v2',amount:all.filter(e=>e.type==='HERO_DAMAGE').reduce((sum,e)=>sum+(e.amount??0),0)});track('commander_damage_total',{model:'v2',amount:all.filter(e=>e.type==='COMMANDER_DAMAGE').reduce((sum,e)=>sum+(e.amount??0),0)});track('battle_duration',{model:'v2',durationMs:Date.now()-startedAt.current});if(mode==='boss')track('boss_attempt_result',{result:next.status,rounds:next.round-1});}}
 function heroCard(id:string|undefined){return id?getCard(id):null;}
 const log=state?.events.slice(-9).reverse()??[];
 return <main className="combat-v2-screen"><header><button type="button" className="combat-v2-back" onClick={onBack}><Icon name="back" size={18}/> Back</button><span className="moon-eyebrow">EXPERIMENTAL · COMBAT V2</span><h1>Three lanes, growing heroes</h1><p>Isolated test rules. No Campaign or Ranked progress is awarded.</p></header>
 {!state?<><nav className="combat-v2-modes" aria-label="Choose combat test">{modes.map(m=><button type="button" key={m.id} className={mode===m.id?'selected':''} onClick={()=>setMode(m.id)}><strong>{m.name}</strong><small>{m.detail}</small></button>)}</nav><div className="combat-v2-note">Your Heroes use their saved Levels and Ascensions. The AI is matched to your average Hero Level. HP persists between lane clashes.</div><button type="button" className="moon-primary combat-v2-start" onClick={start}><Icon name="battle"/> Start {modes.find(m=>m.id===mode)?.name}</button></>:<>
 <div className="combat-v2-status"><span>ROUND {state.round}</span><span>{mode==='boss'?'BOSS ENCOUNTER':mode==='campaign'?'CAMPAIGN SANDBOX':'AI RANKED SANDBOX'}</span><button type="button" onClick={start}>Restart</button></div>
 <div className="combat-v2-commanders"><div><small>YOUR COMMANDER</small><strong>{state.player.commanderHp} HP</strong></div><div><small>{mode==='boss'?'BOSS COMMANDER':'AI COMMANDER'}</small><strong>{state.enemy.commanderHp} HP</strong></div></div>
 <section className="combat-v2-board" aria-label="Three lane combat board">{(['left','center','right'] as const).map(lane=>{const p=heroCard(state.player.heroes[lane]?.cardId),e=heroCard(state.enemy.heroes[lane]?.cardId);return <div className="combat-v2-lane" key={lane}><small>{lane.toUpperCase()}</small><HeroCard card={e} hero={state.enemy.heroes[lane]}/><span className="combat-v2-clash">VS</span><HeroCard card={p} hero={state.player.heroes[lane]}/>{!state.player.heroes[lane]&&state.player.cardsLeft.length>0&&<label className="combat-v2-select">Deploy<select value={choices[lane]} onChange={ev=>setChoices({...choices,[lane]:ev.target.value})}>{state.player.cardsLeft.map((id,index)=><option key={`${id}-${index}`} value={id}>{getCard(id).shortName??getCard(id).name}</option>)}</select></label>}{!state.player.heroes[lane]&&state.player.cardsLeft.length===0&&<small className="combat-v2-no-cards">No Heroes left</small>}</div>})}</section>
 <div className="combat-v2-actions"><label>Spell<select value={spell} onChange={e=>setSpell(e.target.value as typeof spell)}><option value="fireball">Fireball · 10 damage</option><option value="attackUp">Power Surge · +3 ATK</option><option value="attackDown">Weakness · −3 ATK</option><option value="shield">Aegis Ward · shield 10</option></select></label><button className="moon-primary" type="button" disabled={state.status!=='IN_PROGRESS'} onClick={resolve}>{state.status==='IN_PROGRESS'?'Resolve simultaneous round':state.status==='PLAYER_WIN'?'Victory':state.status==='DRAW'?'Draw':'Defeat'}</button></div>
 <div className="combat-v2-events" aria-live="polite">{log.map((event,i)=><span key={`${state.round}-${i}`}>{event.type.replaceAll('_',' ')}{event.amount?` · ${event.amount}`:''}{event.lane?` · ${event.lane}`:''}</span>)}</div>
 </>}
 </main>;
}
function HeroCard({card,hero}:{card:ReturnType<typeof getCard>|null;hero:V2State['player']['heroes'][keyof V2State['player']['heroes']]}){if(!card||!hero)return <div className="combat-v2-empty">OPEN</div>;return <div className="combat-v2-hero"><strong>{card.name}</strong><span>ATK {hero.attack}</span><div className="combat-v2-hp"><i style={{width:`${Math.max(0,hero.hp/hero.maxHp*100)}%`}}/></div><small>HP {Math.max(0,hero.hp)} / {hero.maxHp}{hero.shield?` · SH ${hero.shield}`:''}</small></div>}
