import type { CardDefinition } from '../types/index.js';

// Infernal - demons and fire creatures. Aggression, direct damage, risky Power swings.

export const INFERNAL_CARDS: CardDefinition[] = [
  {
    id: 'inf-flame-imp',
    name: 'Flame Imp',
    shortName: 'Flame Imp',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Demon'],
    boardText: 'Direct hit: +1 damage',
    abilities: [
      {
        trigger: 'ON_DIRECT_DAMAGE',
        actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }],
        text: 'When this deals direct damage, deal 1 extra damage.',
      },
    ],
  },
  {
    id: 'inf-cultist',
    name: 'Infernal Cultist',
    shortName: 'Cultist',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Demon'],
    boardText: 'Before Combat: +1 Power',
    abilities: [
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: gain +1 Power this round.',
      },
    ],
  },
  {
    id: 'inf-pit-fiend',
    name: 'Pit Fiend',
    shortName: 'Pit Fiend',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 2,
    power: 5,
    tags: ['Demon'],
    boardText: 'Death:2dmg; Enemy died:+2',
    abilities: [
      {
        trigger: 'ON_DEATH',
        actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }],
        text: 'On Death: Deal 2 damage to the enemy player.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'ENEMY_DIED_THIS_ROUND' }],
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: if an enemy Hero has died this round, gain +2 Power this round.',
      },
    ],
  },
  {
    id: 'inf-hellhound',
    name: 'Hellhound',
    shortName: 'Hellhound',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 2,
    power: 5,
    tags: ['Demon', 'Beast'],
    boardText: 'On Play: Silence; BC: Enemy-2',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'SILENCE', target: 'ENEMY_SAME_LANE' }],
        text: 'On Play: Silence the enemy Hero in this lane for the rest of the round.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER', amount: -2, duration: 'UNTIL_ROUND_END', target: 'ENEMY_SAME_LANE' }],
        text: 'Before Combat: the enemy Hero in this lane loses 2 Power this round.',
      },
    ],
  },
  {
    id: 'inf-blood-demon',
    name: 'Blood Demon',
    shortName: 'Blood Demon',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 3,
    power: 6,
    tags: ['Demon'],
    boardText: 'Any death:+1; Died:+3 rnd',
    abilities: [
      {
        trigger: 'ON_ALLY_DEATH',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }],
        text: 'When another Hero dies, gain +1 Power.',
      },
      {
        trigger: 'ON_ENEMY_DEATH',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }],
        text: 'When another Hero dies, gain +1 Power.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'ALLY_DIED_THIS_ROUND' }],
        actions: [{ type: 'CHANGE_POWER', amount: 3, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: if an allied Hero died this round, gain +3 Power this round.',
      },
    ],
  },
  {
    id: 'inf-infernal-lord',
    name: 'Infernal Lord',
    shortName: 'Inf. Lord',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 4,
    power: 7,
    tags: ['Demon'],
    boardText: 'All -2; Destroy enemy Spell',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'DEBUFF_ALL_OTHERS', amount: -2, duration: 'UNTIL_ROUND_END' }],
        text: "On Play: every other Hero's Power is reduced by 2 this round.",
      },
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'DESTROY_SPELL_ZONE', target: 'ENEMY_SAME_LANE' }],
        text: 'On Play: also destroy the enemy Continuous Spell in this lane.',
      },
    ],
  },
  // --- Expansion: Mage Slayer / Beast / Trickster ------------------------------------------------------
  {
    id: 'inf-runebreaker',
    name: 'Runebreaker',
    shortName: 'Runebreaker',
    faction: 'infernal',
    type: 'hero',
    role: 'Mage Slayer',
    rarity: 'epic',
    cost: 3,
    power: 5,
    tags: ['Demon', 'Mage Slayer'],
    boardText: 'Dispel; 2nd enemy Spell: 2 dmg',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'DESTROY_SPELL_ZONE', target: 'ENEMY_SAME_LANE' }],
        text: 'On Play: destroy the enemy Continuous Spell in this lane.',
      },
      {
        trigger: 'PASSIVE',
        conditions: [{ type: 'ALLY_TAG_PRESENT', tag: 'Mage Slayer' }],
        actions: [{ type: 'GRANT_IMMUNITY', immunity: 'SPELL', target: 'SELF' }],
        text: 'While another Mage Slayer is in play, this Hero is immune to hostile Spell effects.',
      },
      {
        trigger: 'ON_ENEMY_SPELL_PLAYED',
        oncePerRound: true,
        conditions: [{ type: 'SPELLS_PLAYED_THIS_ROUND_AT_LEAST', count: 2, side: 'ENEMY' }],
        actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }],
        text: 'The second time the enemy plays a Spell each round, deal 2 damage to the enemy player.',
      },
    ],
  },
  {
    id: 'inf-ash-jackal',
    name: 'Ash Jackal',
    shortName: 'Ash Jackal',
    faction: 'infernal',
    type: 'hero',
    role: 'Beast',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Demon', 'Beast'],
    boardText: '+2 per adjacent Beast',
    abilities: [
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'ADJACENT_ALLY_TAG_COUNT', tag: 'Beast', perCount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: gain +2 Power this round for each adjacent allied Beast.',
      },
    ],
  },
  {
    id: 'inf-packhound',
    name: 'Packhound',
    shortName: 'Packhound',
    faction: 'infernal',
    type: 'hero',
    role: 'Beast',
    rarity: 'rare',
    cost: 2,
    power: 4,
    tags: ['Demon', 'Beast'],
    boardText: 'Beast dies: summon Pup',
    abilities: [
      {
        trigger: 'ON_ALLY_DEATH',
        oncePerRound: true,
        conditions: [{ type: 'DEAD_HERO_HAS_TAG', tag: 'Beast' }],
        actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-pup', count: 1 }],
        text: 'When another allied Beast dies, summon a Hound Pup token in an empty lane (once per round).',
      },
    ],
  },
  {
    id: 'inf-alpha-hound',
    name: 'Alpha Hound',
    shortName: 'Alpha Hound',
    faction: 'infernal',
    type: 'hero',
    role: 'Beast',
    rarity: 'epic',
    cost: 3,
    power: 4,
    tags: ['Demon', 'Beast'],
    boardText: '+1 per ally; 3 Heroes: 2 dmg',
    abilities: [
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'ALLY_HERO_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: gain +1 Power this round for each allied Hero (including itself).',
      },
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'ALLY_HERO_COUNT_AT_LEAST', count: 3 }],
        actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }],
        text: 'Before Combat: if you control 3 Heroes, deal 2 damage to the enemy player.',
      },
    ],
  },
  {
    id: 'inf-mirage-imp',
    name: 'Mirage Imp',
    shortName: 'Mirage Imp',
    faction: 'infernal',
    type: 'hero',
    role: 'Trickster',
    rarity: 'rare',
    cost: 2,
    power: 4,
    tags: ['Demon', 'Trickster'],
    boardText: 'Bypass w/ Spell in lane',
    abilities: [
      {
        trigger: 'PASSIVE',
        conditions: [{ type: 'SELF_ENTERED_EARLIER' }, { type: 'SELF_LANE_HAS_SPELL' }],
        actions: [{ type: 'GRANT_BYPASS', reduction: 0 }],
        text: 'Bypass: while your Continuous Spell is in this lane (not the round it enters), this Hero skips combat and deals its full Power as direct damage.',
      },
    ],
  },
];
