import type { CardDefinition } from '../types/index.js';

// Kingdom - knights, priests and archers. Buffs, board control, balance.

export const KINGDOM_CARDS: CardDefinition[] = [
  {
    id: 'kng-common-knight',
    name: 'Common Knight',
    shortName: 'Knight',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 6,
    tags: ['Human', 'Knight'],
    abilities: [],
  },
  {
    id: 'kng-royal-guard',
    name: 'Royal Guard',
    shortName: 'Royal Guard',
    faction: 'kingdom',
    type: 'hero',
    role: 'Support',
    rarity: 'rare',
    cost: 2,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: 'Adj+1; Spell Immune w/ally',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ADJACENT_ALLIES' }],
        text: 'On Play: adjacent allied Heroes gain +1 Power.',
      },
      {
        trigger: 'PASSIVE',
        conditions: [{ type: 'ALLY_FACTION_PRESENT', faction: 'kingdom' }],
        actions: [{ type: 'GRANT_IMMUNITY', immunity: 'SPELL', target: 'SELF' }],
        text: 'While another Kingdom Hero is in play, this Hero is immune to hostile Spell effects.',
      },
    ],
  },
  {
    id: 'kng-light-priest',
    name: 'Light Priest',
    shortName: 'Light Priest',
    faction: 'kingdom',
    type: 'hero',
    role: 'Support',
    rarity: 'rare',
    cost: 2,
    power: 3,
    tags: ['Human'],
    boardText: 'Heal3+Shield; Spell: +1',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'PLAYER_HEAL', amount: 3 }],
        text: 'On Play: Heal your player for 3.',
      },
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'GRANT_SHIELD', target: 'SELF' }],
        text: 'On Play: this Hero gains a shield - the first time it would be destroyed, that destruction is prevented instead.',
      },
      {
        trigger: 'ON_ALLY_SPELL_PLAYED',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Whenever you play a Spell, gain +1 Power this round.',
      },
    ],
  },
  {
    id: 'kng-archer',
    name: 'Kingdom Archer',
    shortName: 'Archer',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human'],
    boardText: '+2 with Spell in lane',
    abilities: [
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'SELF_LANE_HAS_SPELL' }],
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: if your Continuous Spell is in this lane, gain +2 Power this round.',
      },
    ],
  },
  {
    id: 'kng-battle-captain',
    name: 'Battle Captain',
    shortName: 'Battle Captain',
    faction: 'kingdom',
    type: 'hero',
    role: 'Support',
    rarity: 'epic',
    cost: 3,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: 'Allies +1; Immune w/ Knight',
    abilities: [
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'ALL_ALLIES' }],
        text: 'Before Combat: All allied Heroes gain +1 Power this round.',
      },
      {
        trigger: 'PASSIVE',
        conditions: [{ type: 'ALLY_TAG_PRESENT', tag: 'Knight' }],
        actions: [{ type: 'GRANT_IMMUNITY', immunity: 'HERO_EFFECT', target: 'SELF' }],
        text: 'While another Knight is in play, this Hero is immune to hostile Hero abilities.',
      },
    ],
  },
  {
    id: 'kng-paladin',
    name: 'Legendary Paladin',
    shortName: 'Paladin',
    faction: 'kingdom',
    type: 'hero',
    role: 'Tank',
    rarity: 'legendary',
    cost: 3,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: 'Shield; +4 losing; -2 overflow',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'GRANT_SHIELD', target: 'SELF' }],
        text: 'On Play: this Hero gains a shield - the first time it would be destroyed, that destruction is prevented instead.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'SELF_LOSING_LANE' }],
        actions: [{ type: 'CHANGE_POWER', amount: 4, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: if this Hero would lose its lane, gain +4 Power this round.',
      },
      {
        trigger: 'PASSIVE',
        actions: [{ type: 'REDUCE_OVERFLOW_DAMAGE', amount: 2, target: 'SELF' }],
        text: 'If this Hero loses its lane, the overflow damage you take from it is reduced by 2.',
      },
    ],
  },
  // --- Expansion: Mage (Spell deck) --------------------------------------------------------------
  {
    id: 'kng-apprentice-mage',
    name: 'Apprentice Mage',
    shortName: 'Apprentice',
    faction: 'kingdom',
    type: 'hero',
    role: 'Mage',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human', 'Mage'],
    boardText: 'Spell played: +2 this rd',
    abilities: [
      {
        trigger: 'ON_ALLY_SPELL_PLAYED',
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Whenever you play a Spell, gain +2 Power this round.',
      },
    ],
  },
  {
    id: 'kng-archmage-vael',
    name: 'Archmage Vael',
    shortName: 'Vael',
    faction: 'kingdom',
    type: 'hero',
    role: 'Archmage',
    rarity: 'legendary',
    cost: 4,
    power: 4,
    tags: ['Human', 'Mage'],
    boardText: '1st Spell twice; 2nd: 2 dmg',
    abilities: [
      {
        trigger: 'PASSIVE',
        actions: [{ type: 'SPELL_ECHO' }],
        text: 'The first one-time Spell you play each round resolves twice.',
      },
      {
        trigger: 'ON_ALLY_SPELL_PLAYED',
        oncePerRound: true,
        conditions: [{ type: 'SPELLS_PLAYED_THIS_ROUND_AT_LEAST', count: 2 }],
        actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }],
        text: 'The second time you play a Spell each round, deal 2 damage to the enemy player.',
      },
    ],
  },
  // --- Expansion: Mage Slayer (anti-Spell) ---------------------------------------------------------
  {
    id: 'kng-spellbreaker',
    name: 'Spellbreaker',
    shortName: 'Spellbreaker',
    faction: 'kingdom',
    type: 'hero',
    role: 'Mage Slayer',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human', 'Knight', 'Mage Slayer'],
    boardText: 'Enemy Spell: +2 this round',
    abilities: [
      {
        trigger: 'ON_ENEMY_SPELL_PLAYED',
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Whenever the enemy plays a Spell, gain +2 Power this round.',
      },
    ],
  },
  {
    id: 'kng-null-templar',
    name: 'Null Templar',
    shortName: 'Null Templar',
    faction: 'kingdom',
    type: 'hero',
    role: 'Mage Slayer',
    rarity: 'rare',
    cost: 2,
    power: 5,
    tags: ['Human', 'Knight', 'Mage Slayer'],
    boardText: 'Blocks 1st Spell each round',
    abilities: [
      {
        trigger: 'PASSIVE',
        oncePerRound: true,
        actions: [{ type: 'GRANT_IMMUNITY', immunity: 'SPELL', target: 'SELF' }],
        text: 'The first hostile Spell that would affect this Hero each round has no effect.',
      },
    ],
  },
];
