import type { CardDefinition } from '../types/index.js';

// The 63 cards the Moonwater launch set adds (docs/BOX-ARCHITECTURE.md, the 116-card roster in launchRoster.ts).
//
// Authored for card combat only: one-time Spells resolve on CAST, every Continuous Spell names its binding, and amounts
// use the engine's units (CHANGE_POWER steps of 15 ATK, PLAYER_DAMAGE / PLAYER_HEAL legacy points of 45 HP). Printed
// ATK comes from the launch roster (stats.ts), so `power` here is only the Power line the legacy resolver and the
// Graveyard picks read. An ability with empty text continues the line above it (Ignis, Enfeeble).

export const LAUNCH_CARDS: CardDefinition[] = [
  {
    id: 'kng-shieldbearer',
    name: 'Shieldbearer',
    shortName: 'Shieldbearer',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Human', 'Knight'],
    boardText: 'Guard 2',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Guard 2: Before Combat, if this Unit would lose its lane, gain +30 ATK this round.' },
    ],
  },
  {
    id: 'und-ghoul-brute',
    name: 'Ghoul Brute',
    shortName: 'Ghoul Brute',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 6,
    tags: ['Undead'],
    abilities: [],
  },
  {
    id: 'und-grave-sexton',
    name: 'Grave Sexton',
    shortName: 'Grave Sexton',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Undead'],
    boardText: '3+ Grave Units: Heal 45',
    abilities: [
      { trigger: 'ROUND_END', conditions: [{ type: 'GRAVEYARD_COUNT_AT_LEAST', count: 3, units: true }], actions: [{ type: 'PLAYER_HEAL', amount: 1 }], text: 'Round End: if your Graveyard has 3+ Units, restore 45 HP.' },
    ],
  },
  {
    id: 'inf-brimstone-ogre',
    name: 'Brimstone Ogre',
    shortName: 'Brimstone Ogre',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 6,
    tags: ['Demon'],
    abilities: [],
  },
  {
    id: 'inf-soot-imp',
    name: 'Soot Imp',
    shortName: 'Soot Imp',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Demon'],
    boardText: 'Death: 45 damage',
    abilities: [
      { trigger: 'ON_DEATH', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Destroyed: deal 45 damage.' },
    ],
  },
  {
    id: 'spl-cinder-bolt',
    name: 'Cinder Bolt',
    shortName: 'Cinder Bolt',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Deal 90 damage',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }], text: 'Deal 90 damage.' },
    ],
  },
  {
    id: 'kng-marshal-aldric',
    name: 'Marshal Aldric',
    shortName: 'Marshal Aldric',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: '3 Units: others +15; Shield',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'ALLY_HERO_COUNT_AT_LEAST', count: 3 }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'ALL_ALLIES' }, { type: 'CHANGE_POWER', amount: -1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Clash: if you control 3 Units, your other Units gain +15 ATK this round.' },
      { trigger: 'ON_ALLY_DEATH', actions: [{ type: 'GRANT_SHIELD', target: 'SELF' }], oncePerRound: true, text: 'Ally Falls: gain a Shield (once per round).' },
    ],
  },
  {
    id: 'kng-oathkeeper',
    name: 'Oathkeeper',
    shortName: 'Oathkeeper',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Human', 'Knight'],
    boardText: 'Shield; Guard 1 w/ 3 Units',
    abilities: [
      { trigger: 'PASSIVE', actions: [{ type: 'GRANT_SHIELD', target: 'SELF' }], text: 'This Unit has a Shield: the first time it would be destroyed, it survives instead.' },
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }, { type: 'ALLY_HERO_COUNT_AT_LEAST', count: 3 }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Guard 1: Before Combat, if you control 3 Units and this Unit would lose its lane, gain +15 ATK this round.' },
    ],
  },
  {
    id: 'kng-knight-errant',
    name: 'Knight-Errant',
    shortName: 'Knight-Errant',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Human', 'Knight'],
    boardText: '+15 per other Knight',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'OTHER_ALLY_TAG_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF', max: 2, tag: 'Knight' }], text: 'Clash: +15 ATK this round for each other Knight you control.' },
    ],
  },
  {
    id: 'kng-relic-warden',
    name: 'Relic Warden',
    shortName: 'Relic Warden',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human', 'Knight'],
    boardText: 'Clash: exile enemy Grave Unit',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'EXILE_FROM_GRAVEYARD', pick: 'HIGHEST_POWER' }], text: 'Clash: exile the strongest Unit in the enemy Graveyard.' },
    ],
  },
  {
    id: 'kng-pikeman',
    name: 'Pikeman',
    shortName: 'Pikeman',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human'],
    boardText: '+15 per adjacent Knight',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'ADJACENT_ALLY_TAG_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF', max: 2, tag: 'Knight' }], text: 'Clash: +15 ATK this round for each adjacent Knight.' },
    ],
  },
  {
    id: 'und-morwen',
    name: 'Morwen, Lich Queen',
    shortName: 'Morwen',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Mage'],
    boardText: 'Guard 2; shore up; revive',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Guard 2: Before Combat, if this Unit would lose its lane, gain +30 ATK this round.' },
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'ADJACENT_ALLIES_LOSING' }], text: 'Clash: each adjacent ally that would lose its lane gains +15 ATK this round.' },
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'REVIVE_TO_LANE', emptyLane: true, maxPower: Infinity, pick: 'LOWEST_POWER', faction: 'undead' }], text: 'Clash: revive your weakest Undead Unit from your Graveyard in an empty lane.' },
    ],
  },
  {
    id: 'und-bonecaller',
    name: 'Bonecaller',
    shortName: 'Bonecaller',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Undead'],
    boardText: 'Undead falls: +15 (max +45)',
    abilities: [
      { trigger: 'ON_ALLY_DEATH', conditions: [{ type: 'DEAD_HERO_HAS_TAG', tag: 'Undead' }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Ally Falls: if it was Undead, this Unit gains +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'und-skeletal-legionnaire',
    name: 'Skeletal Legionnaire',
    shortName: 'Skeletal Legionnaire',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Skeleton', 'Undead'],
    boardText: 'Death: summon Skeleton',
    abilities: [
      { trigger: 'ON_DEATH', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-skeleton', count: 1 }], text: 'Destroyed: summon a Skeleton (65 ATK) in an empty lane.' },
    ],
  },
  {
    id: 'spl-bone-wall',
    name: 'Bone Wall',
    shortName: 'Bone Wall',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Shield; +30 w/ 3+ Grave Units',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'GRANT_SHIELD', target: 'ALLY_SAME_LANE' }], text: 'Your Unit here gains a Shield.' },
      { trigger: 'CAST', conditions: [{ type: 'GRAVEYARD_COUNT_AT_LEAST', count: 3, units: true }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'ALLY_SAME_LANE' }], text: 'If your Graveyard has 3+ Units, it also gains +30 ATK this round.' },
    ],
  },
  {
    id: 'und-rattling-horde',
    name: 'Rattling Horde',
    shortName: 'Rattling Horde',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 3,
    tags: ['Skeleton', 'Undead'],
    boardText: '+15 per Undead you control',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'ALLY_FACTION_HERO_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF', max: 3, faction: 'undead' }], text: 'Clash: +15 ATK this round for each Undead Unit you control (including this one).' },
    ],
  },
  {
    id: 'inf-cerberus',
    name: 'Cerberus, Gate Hound',
    shortName: 'Cerberus',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Demon', 'Beast'],
    boardText: '3 Units: enemies −15; Pup',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'ALLY_HERO_COUNT_AT_LEAST', count: 3 }], actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'UNTIL_ROUND_END', target: 'ALL_ENEMIES' }], text: 'Clash: if you control 3 Units, every enemy Unit gets −15 ATK this round.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-pup', count: 1 }], text: 'Destroyed: summon a Hound Pup (65 ATK) in an empty lane.' },
    ],
  },
  {
    id: 'inf-brimstone-matriarch',
    name: 'Brimstone Matriarch',
    shortName: 'Brimstone Matriarch',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 5,
    tags: ['Demon', 'Beast'],
    boardText: '3 Units: +15; Death: Pup',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'ALLY_HERO_COUNT_AT_LEAST', count: 3 }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Clash: +15 ATK this round if you control 3 Units.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-pup', count: 1 }], text: 'Destroyed: summon a Hound Pup (65 ATK) in an empty lane.' },
    ],
  },
  {
    id: 'spl-call-the-pack',
    name: 'Call the Pack',
    shortName: 'Call the Pack',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Summon Pup; draw',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-pup', count: 1 }], text: 'Summon a Hound Pup (65 ATK) in an empty lane.' },
      { trigger: 'CAST', actions: [{ type: 'DRAW_CARDS', count: 1 }], text: 'Draw a card.' },
    ],
  },
  {
    id: 'inf-cinder-jackal',
    name: 'Cinder Jackal',
    shortName: 'Cinder Jackal',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Demon', 'Beast'],
    boardText: 'Death: summon Hound Pup',
    abilities: [
      { trigger: 'ON_DEATH', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-pup', count: 1 }], text: 'Destroyed: summon a Hound Pup (65 ATK) in an empty lane.' },
    ],
  },
  {
    id: 'kng-moonlit-savant',
    name: 'Moonlit Savant',
    shortName: 'Moonlit Savant',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Human', 'Mage'],
    boardText: 'Spell: +15 (max +45)',
    abilities: [
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Your Spell: this Unit gains +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'spl-mirror-image',
    name: 'Mirror Image',
    shortName: 'Mirror Image',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'epic',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Return a Spell; draw',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'RANDOM', cardType: 'spell' }], text: 'Return a random Spell from your Graveyard to your hand.' },
      { trigger: 'CAST', actions: [{ type: 'DRAW_CARDS', count: 1 }], text: 'Draw a card.' },
    ],
  },
  {
    id: 'kng-battlemage',
    name: 'Battlemage',
    shortName: 'Battlemage',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 5,
    tags: ['Human', 'Mage'],
    boardText: 'Spell: enemy here −30',
    abilities: [
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'CHANGE_POWER', amount: -2, duration: 'UNTIL_ROUND_END', target: 'ENEMY_SAME_LANE' }], text: 'Your Spell: the enemy here gets −30 ATK this round.' },
    ],
  },
  {
    id: 'spl-arcane-barrier',
    name: 'Arcane Barrier',
    shortName: 'Arcane Barrier',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Shield your Unit; draw',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'GRANT_SHIELD', target: 'ALLY_SAME_LANE' }], text: 'Your Unit here gains a Shield.' },
      { trigger: 'CAST', actions: [{ type: 'DRAW_CARDS', count: 1 }], text: 'Draw a card.' },
    ],
  },
  {
    id: 'spl-spark',
    name: 'Spark',
    shortName: 'Spark',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Deal 45; draw',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Deal 45 damage.' },
      { trigger: 'CAST', actions: [{ type: 'DRAW_CARDS', count: 1 }], text: 'Draw a card.' },
    ],
  },
  {
    id: 'und-duchess-nyx',
    name: 'Duchess Nyx',
    shortName: 'Duchess Nyx',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Undead', 'Trickster'],
    boardText: 'Bypass w/ Continuous Spell',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 1 }, { type: 'SELF_ENTERED_EARLIER' }], actions: [{ type: 'GRANT_BYPASS', reduction: 0 }], text: 'Bypass while you control a Continuous Spell, from next round.' },
      { trigger: 'ROUND_END', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_MOST', count: 0 }], actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'RANDOM', cardType: 'spell' }], text: 'Round End: if you control no Continuous Spell, gain a random Graveyard Spell.' },
      { trigger: 'ON_DIRECT_DAMAGE', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Direct Attack: +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'und-banshee',
    name: 'Banshee',
    shortName: 'Banshee',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Trickster'],
    boardText: 'Bypass w/ 2 Spells',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 2 }, { type: 'SELF_ENTERED_EARLIER' }], actions: [{ type: 'GRANT_BYPASS', reduction: 0 }], text: 'Bypass while you control 2+ Continuous Spells, from next round.' },
      { trigger: 'ON_DIRECT_DAMAGE', actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'RANDOM', cardType: 'spell' }], oncePerRound: true, text: 'Direct Attack: gain a random Graveyard Spell.' },
    ],
  },
  {
    id: 'und-spectral-assassin',
    name: 'Spectral Assassin',
    shortName: 'Spectral Assassin',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 5,
    tags: ['Undead', 'Trickster'],
    boardText: 'Bypass −30 w/ Spell',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 1 }, { type: 'SELF_ENTERED_EARLIER' }], actions: [{ type: 'GRANT_BYPASS', reduction: 2 }], text: 'Bypass at −30 ATK while you control a Continuous Spell, from next round.' },
    ],
  },
  {
    id: 'spl-ghost-lantern',
    name: 'Ghost Lantern',
    shortName: 'Ghost Lantern',
    faction: 'undead',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    spellBinding: 'LANE',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Your Unit here +15',
    abilities: [
      { trigger: 'CONTINUOUS', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }], text: 'Lane: your Unit here has +15 ATK.' },
    ],
  },
  {
    id: 'inf-ignis',
    name: 'Ignis, Ashen Crown',
    shortName: 'Ignis',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Demon'],
    boardText: 'Round End: 45 per Spell',
    abilities: [
      { trigger: 'ROUND_END', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 1 }], actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Round End: deal 45 damage for each Continuous Spell you control.' },
      { trigger: 'ROUND_END', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 2 }], actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: '' },
      { trigger: 'ROUND_END', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 3 }], actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: '' },
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Your Spell: +15 ATK this round.' },
    ],
  },
  {
    id: 'inf-hellfire-warlock',
    name: 'Hellfire Warlock',
    shortName: 'Hellfire Warlock',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Demon', 'Mage'],
    boardText: '2nd Spell: 90; Death: 45',
    abilities: [
      { trigger: 'ON_ALLY_SPELL_PLAYED', conditions: [{ type: 'SPELLS_PLAYED_THIS_ROUND_AT_LEAST', count: 2 }], actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }], oncePerRound: true, text: 'Your 2nd Spell: deal 90 damage.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Destroyed: deal 45 damage.' },
    ],
  },
  {
    id: 'spl-inferno',
    name: 'Inferno',
    shortName: 'Inferno',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'epic',
    cost: 1,
    tags: ['Spell'],
    boardText: '45 damage; enemies −15',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Deal 45 damage.' },
      { trigger: 'CAST', actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ALL_ENEMIES' }], text: 'Every enemy Unit gets −15 ATK.' },
    ],
  },
  {
    id: 'inf-ember-witch',
    name: 'Ember Witch',
    shortName: 'Ember Witch',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Demon', 'Mage'],
    boardText: 'Spell: 45 damage (1/round)',
    abilities: [
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], oncePerRound: true, text: 'Your Spell: deal 45 damage (once per round).' },
    ],
  },
  {
    id: 'inf-cinder-imp',
    name: 'Cinder Imp',
    shortName: 'Cinder Imp',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Demon'],
    boardText: 'Losing: deal 45',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Clash: if this Unit would lose its lane, deal 45 damage.' },
    ],
  },
  {
    id: 'spl-wall-of-flame',
    name: 'Wall of Flame',
    shortName: 'Wall of Flame',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    spellBinding: 'LANE',
    role: 'Spell',
    rarity: 'rare',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Enemy here −15',
    abilities: [
      { trigger: 'CONTINUOUS', actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }], text: 'Lane: the enemy here has −15 ATK.' },
    ],
  },
  {
    id: 'kng-saint-aveline',
    name: 'Saint Aveline',
    shortName: 'Saint Aveline',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 4,
    tags: ['Human'],
    boardText: 'Attached Spells return',
    abilities: [
      { trigger: 'PASSIVE', actions: [{ type: 'RETURN_EXPIRED_ATTACHED' }], text: 'Passive: when one of your Attached Spells expires, return it to your hand (once per round).' },
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Your Spell: +15 ATK this round.' },
    ],
  },
  {
    id: 'kng-crusader-champion',
    name: 'Crusader Champion',
    shortName: 'Crusader Champion',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: '+30, Spell Immune w/ Spell',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SELF_LANE_HAS_SPELL' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'PERMANENT', target: 'SELF' }], text: 'Passive: +30 ATK while your Continuous Spell is in this lane.' },
      { trigger: 'PASSIVE', conditions: [{ type: 'SELF_LANE_HAS_SPELL' }], actions: [{ type: 'GRANT_IMMUNITY', immunity: 'SPELL', target: 'SELF' }], text: 'Passive: enemy Spells can’t affect it while your Continuous Spell is in this lane.' },
    ],
  },
  {
    id: 'spl-oath-blade',
    name: 'Oath Blade',
    shortName: 'Oath Blade',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    spellBinding: 'UNIT',
    role: 'Spell',
    rarity: 'rare',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Attached +15; Heal 45',
    abilities: [
      { trigger: 'CONTINUOUS', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }], text: 'Attached: the attached Unit has +15 ATK.' },
      { trigger: 'ROUND_END', actions: [{ type: 'PLAYER_HEAL', amount: 1 }], text: 'Round End: restore 45 HP.' },
    ],
  },
  {
    id: 'kng-standard-bearer',
    name: 'Standard Bearer',
    shortName: 'Standard Bearer',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Human'],
    boardText: 'Adjacent +15 w/ Spell here',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SELF_LANE_HAS_SPELL' }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ADJACENT_ALLIES' }], text: 'Passive: adjacent allies have +15 ATK while your Continuous Spell is in this lane.' },
    ],
  },
  {
    id: 'spl-consecrate',
    name: 'Consecrate',
    shortName: 'Consecrate',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Your Unit here +15',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }], text: 'Your Unit here gains +15 ATK for the rest of the battle.' },
    ],
  },
  {
    id: 'kng-oath-acolyte',
    name: 'Acolyte of the Oath',
    shortName: 'Acolyte of the Oath',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Human'],
    boardText: 'Heal 45 w/ Spell here',
    abilities: [
      { trigger: 'ROUND_END', conditions: [{ type: 'SELF_LANE_HAS_SPELL' }], actions: [{ type: 'PLAYER_HEAL', amount: 1 }], text: 'Round End: if your Continuous Spell is in this lane, restore 45 HP.' },
    ],
  },
  {
    id: 'und-plague-mother',
    name: 'The Plague Mother',
    shortName: 'The Plague Mother',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 4,
    tags: ['Undead'],
    boardText: 'Shield; Guard 1; here −15+',
    abilities: [
      { trigger: 'PASSIVE', actions: [{ type: 'GRANT_SHIELD', target: 'SELF' }], text: 'This Unit has a Shield: the first time it would be destroyed, it survives instead.' },
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Guard 1: Before Combat, if this Unit would lose its lane, gain +15 ATK this round.' },
      // Wither gate (2026-10-09): she weakens the enemy in her own lane, and only spreads to enemies that already have lasting ATK loss.
      {
        trigger: 'ROUND_END',
        actions: [
          { type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' },
          { type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'OTHER_ENEMIES_WITH_LASTING_LOSS' },
        ],
        text: 'Round End: the enemy here gets −15 ATK for the rest of the battle, and every other enemy Unit with lasting ATK loss gets −15 ATK more.',
      },
    ],
  },
  {
    id: 'und-blightcaster',
    name: 'Blightcaster',
    shortName: 'Blightcaster',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Mage'],
    boardText: 'Enemy here −15; Heal 45',
    abilities: [
      { trigger: 'ROUND_END', actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }], text: 'Round End: the enemy here gets −15 ATK for the rest of the battle.' },
      { trigger: 'ON_ENEMY_DEATH', actions: [{ type: 'PLAYER_HEAL', amount: 1 }], oncePerRound: true, text: 'Enemy Falls: restore 45 HP (once per round).' },
    ],
  },
  {
    id: 'und-withering-lich',
    name: 'Withering Lich',
    shortName: 'Withering Lich',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 5,
    tags: ['Undead', 'Mage'],
    boardText: 'Enemy falls: +15 (max +45)',
    abilities: [
      { trigger: 'ON_ENEMY_DEATH', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Enemy Falls: this Unit gains +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'und-rot-ghoul',
    name: 'Rot Ghoul',
    shortName: 'Rot Ghoul',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Undead'],
    boardText: 'Death: enemy here −30',
    abilities: [
      { trigger: 'ON_DEATH', actions: [{ type: 'CHANGE_POWER', amount: -2, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }], text: 'Destroyed: the enemy here gets −30 ATK for the rest of the battle.' },
    ],
  },
  {
    id: 'spl-enfeeble',
    name: 'Enfeeble',
    shortName: 'Enfeeble',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Enemy −30 now, −15 lasting',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'CHANGE_POWER', amount: -2, duration: 'UNTIL_ROUND_END', target: 'ENEMY_SAME_LANE' }], text: 'Enemy here −30 ATK this round and −15 ATK for the rest of the battle.' },
      { trigger: 'CAST', actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }], text: '' },
    ],
  },
  {
    id: 'inf-kathra',
    name: 'Kathra, Blood Queen',
    shortName: 'Kathra',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Demon'],
    boardText: 'Ally falls +15; own kill 45',
    abilities: [
      // Sacrifice gate (2026-10-09): any death still grows her; only a death your own effect caused deals damage.
      { trigger: 'ON_ALLY_DEATH', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Ally Falls: this Unit gains +15 ATK (up to +45).' },
      { trigger: 'ON_ALLY_DEATH', conditions: [{ type: 'DEATH_BY_OWN_EFFECT' }], actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'When one of your own cards destroys one of your Units: deal 45 damage.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }], text: 'Destroyed: deal 90 damage.' },
    ],
  },
  {
    id: 'spl-flesh-altar',
    name: 'Flesh Altar',
    shortName: 'Flesh Altar',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    spellBinding: 'LANE',
    role: 'Spell',
    rarity: 'epic',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Ally falls: Unit here +15',
    abilities: [
      { trigger: 'ON_ALLY_DEATH', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }], text: 'Lane: when one of your Units falls, your Unit here gains +15 ATK for the rest of the battle.' },
    ],
  },
  {
    id: 'inf-blood-imp',
    name: 'Blood Imp',
    shortName: 'Blood Imp',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 5,
    tags: ['Demon'],
    boardText: 'Death: others +15',
    abilities: [
      { trigger: 'ON_DEATH', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALL_ALLIES' }], text: 'Destroyed: your other Units gain +15 ATK for the rest of the battle.' },
    ],
  },
  {
    id: 'inf-blood-thrall',
    name: 'Blood Thrall',
    shortName: 'Blood Thrall',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Demon'],
    boardText: 'Losing: deal 90',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }], text: 'Clash: if this Unit would lose its lane, deal 90 damage.' },
    ],
  },
  {
    id: 'spl-dark-ritual',
    name: 'Dark Ritual',
    shortName: 'Dark Ritual',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Destroy your Unit; draw 2',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'DESTROY', target: 'ALLY_SAME_LANE' }], text: 'Destroy your Unit here.' },
      { trigger: 'CAST', actions: [{ type: 'DRAW_CARDS', count: 2 }], text: 'Draw 2 cards.' },
    ],
  },
  {
    id: 'und-bone-dragon',
    name: 'Bone Dragon',
    shortName: 'Bone Dragon',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Skeleton', 'Undead'],
    boardText: '+15 per Grave Unit (max +45)',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'GRAVEYARD_UNIT_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF', max: 3 }], text: 'Clash: +15 ATK this round per Unit in your Graveyard (up to +45).' },
    ],
  },
  {
    id: 'und-barrow-knight',
    name: 'Barrow Knight',
    shortName: 'Barrow Knight',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Knight'],
    boardText: 'Guard 1; Skeleton; Spell +30',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SELF_LOSING_LANE' }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Guard 1: Before Combat, if this Unit would lose its lane, gain +15 ATK this round.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-skeleton', count: 1 }], text: 'Destroyed: summon a Skeleton (65 ATK) in an empty lane.' },
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'SPELL_PLAYED_THIS_ROUND', side: 'ENEMY' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Clash: +30 ATK this round if the enemy cast a Spell this round.' },
    ],
  },
  {
    id: 'inf-flame-herald',
    name: 'Flame Herald',
    shortName: 'Flame Herald',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Demon'],
    boardText: 'Clash: deal 45',
    abilities: [
      { trigger: 'BEFORE_COMBAT', actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }], text: 'Clash: deal 45 damage.' },
    ],
  },
  {
    id: 'spl-meteor',
    name: 'Meteor',
    shortName: 'Meteor',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'epic',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Destroy 110 or less; 90 dmg',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'DESTROY', target: 'ENEMY_SAME_LANE', maxPower: 5 }], text: 'Destroy the enemy here if it has 110 ATK or less.' },
      { trigger: 'CAST', actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }], text: 'Deal 90 damage.' },
    ],
  },
  {
    id: 'kng-banner-knight',
    name: 'Banner Knight',
    shortName: 'Banner Knight',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 5,
    tags: ['Human', 'Knight'],
    boardText: 'Spell here: +15 (max +45)',
    abilities: [
      { trigger: 'ROUND_END', conditions: [{ type: 'SELF_LANE_HAS_SPELL' }], actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Round End: if your Continuous Spell is in this lane, gain +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'spl-reliquary-blade',
    name: 'Reliquary Blade',
    shortName: 'Reliquary Blade',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    spellBinding: 'UNIT',
    role: 'Spell',
    rarity: 'epic',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Attached: +30 ATK',
    abilities: [
      { trigger: 'CONTINUOUS', actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }], text: 'Attached: the attached Unit has +30 ATK.' },
    ],
  },
  {
    id: 'und-grave-tyrant',
    name: 'The Grave Tyrant',
    shortName: 'The Grave Tyrant',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'legendary',
    cost: 1,
    power: 5,
    tags: ['Undead'],
    boardText: 'Exile enemy Grave; +15',
    abilities: [
      { trigger: 'ROUND_END', actions: [{ type: 'EXILE_FROM_GRAVEYARD', pick: 'HIGHEST_POWER' }, { type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Round End: exile the strongest Unit in the enemy Graveyard and gain +15 ATK (up to +45).' },
    ],
  },
  {
    id: 'und-ashen-revenant',
    name: 'Ashen Revenant',
    shortName: 'Ashen Revenant',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Demon'],
    boardText: 'Ally falls: +15; returns',
    abilities: [
      { trigger: 'ON_ALLY_DEATH', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }], text: 'Ally Falls: +15 ATK (up to +45).' },
      { trigger: 'ON_DEATH', actions: [{ type: 'RETURN_DEATH_SOURCE_TO_HAND' }], text: 'Destroyed: return this card to your hand (once).' },
    ],
  },
  {
    id: 'kng-arcane-knight',
    name: 'Arcane Knight',
    shortName: 'Arcane Knight',
    faction: 'kingdom',
    type: 'hero',
    role: 'Fighter',
    rarity: 'epic',
    cost: 1,
    power: 5,
    tags: ['Human', 'Knight', 'Mage'],
    boardText: 'Spell: adjacent +15',
    abilities: [
      { trigger: 'ON_ALLY_SPELL_PLAYED', actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'ADJACENT_ALLIES' }], oncePerRound: true, text: 'Your Spell: adjacent allies gain +15 ATK this round.' },
    ],
  },
  {
    id: 'und-night-courier',
    name: 'Night Courier',
    shortName: 'Night Courier',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 4,
    tags: ['Undead', 'Trickster'],
    boardText: 'Bypass w/ Spell; regain Spell',
    abilities: [
      { trigger: 'PASSIVE', conditions: [{ type: 'SPELL_ZONES_OCCUPIED_AT_LEAST', count: 1 }, { type: 'SELF_ENTERED_EARLIER' }], actions: [{ type: 'GRANT_BYPASS', reduction: 0 }], text: 'Bypass while you have a Continuous Spell, from next round.' },
      { trigger: 'ON_DEATH', actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'RANDOM', cardType: 'spell' }], text: 'Destroyed: gain a random Graveyard Spell.' },
    ],
  },
  {
    id: 'inf-pack-warden',
    name: 'Pack Warden',
    shortName: 'Pack Warden',
    faction: 'infernal',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 1,
    power: 5,
    tags: ['Demon', 'Beast'],
    boardText: '+30 with adjacent ally',
    abilities: [
      { trigger: 'BEFORE_COMBAT', conditions: [{ type: 'ADJACENT_ALLY_PRESENT' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }], text: 'Clash: +30 ATK this round if an ally is adjacent.' },
    ],
  },
  {
    id: 'spl-oath-of-vengeance',
    name: 'Oath of Vengeance',
    shortName: 'Oath of Vengeance',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 1,
    tags: ['Spell'],
    boardText: '+30; +30 more if ally fell',
    abilities: [
      { trigger: 'CAST', actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'ALLY_SAME_LANE' }], text: 'Your Unit here +30 ATK this round.' },
      { trigger: 'CAST', conditions: [{ type: 'ALLY_DIED_THIS_ROUND' }], actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'ALLY_SAME_LANE' }], text: 'If an ally fell this round, +30 more.' },
    ],
  },
];

/** The cards new in the launch set. They have no legacy rules of their own: every surface reads their card-combat rules. */
export const LAUNCH_NEW_CARD_IDS: ReadonlySet<string> = new Set(LAUNCH_CARDS.map((c) => c.id));
