/** Original portraits generated for this pass. Existing Core / Vael portraits are retained. */
export const LAUNCH_PORTRAITS = [
  'kng-marshal-aldric', 'und-morwen', 'inf-cerberus', 'und-duchess-nyx',
  'inf-ignis', 'kng-saint-aveline', 'und-plague-mother', 'inf-kathra', 'und-grave-tyrant',
  'und-bone-dragon', 'und-banshee', 'inf-brimstone-matriarch', 'und-blightcaster',
] as const;

/** Deliberate shared illustrations for V1, not the missing-image fallback. Each entry names its source.
 * Keep Legendary portraits exclusive; replace these aliases with unique art in a later art pass. */
export const SHARED_CARD_ART: Readonly<Record<string, string>> = {
  'kng-shieldbearer': 'kng-royal-guard',
  'kng-oathkeeper': 'kng-null-templar',
  'kng-knight-errant': 'kng-common-knight',
  'kng-relic-warden': 'kng-spellbreaker',
  'kng-pikeman': 'kng-battle-captain',
  'kng-moonlit-savant': 'kng-apprentice-mage',
  'kng-battlemage': 'kng-spellbreaker',
  'kng-crusader-champion': 'kng-null-templar',
  'kng-standard-bearer': 'kng-battle-captain',
  'kng-oath-acolyte': 'kng-light-priest',
  'kng-banner-knight': 'kng-battle-captain',
  'kng-arcane-knight': 'kng-spellbreaker',
  'und-ghoul-brute': 'und-cursed-warrior',
  'und-grave-sexton': 'und-grave-sage',
  'und-bonecaller': 'und-dark-priest',
  'und-skeletal-legionnaire': 'und-bone-soldier',
  'und-rattling-horde': 'und-bone-soldier',
  'und-spectral-assassin': 'und-shade-thief',
  'und-withering-lich': 'und-blightcaster',
  'und-rot-ghoul': 'und-cursed-warrior',
  'und-barrow-knight': 'und-crypt-warden',
  'und-ashen-revenant': 'und-grave-knight',
  'und-night-courier': 'und-shade-thief',
  'inf-brimstone-ogre': 'inf-pit-fiend',
  'inf-soot-imp': 'inf-mirage-imp',
  'inf-cinder-jackal': 'inf-ash-jackal',
  'inf-hellfire-warlock': 'inf-cultist',
  'inf-ember-witch': 'inf-blood-demon',
  'inf-cinder-imp': 'inf-mirage-imp',
  'inf-blood-imp': 'inf-mirage-imp',
  'inf-blood-thrall': 'inf-cultist',
  'inf-flame-herald': 'inf-cultist',
  'inf-pack-warden': 'inf-alpha-hound',
  'spl-cinder-bolt': 'spl-fireball',
  'spl-bone-wall': 'spl-grave-totem',
  'spl-call-the-pack': 'tok-pup',
  'spl-mirror-image': 'spl-stasis-field',
  'spl-arcane-barrier': 'spl-ward-circle',
  'spl-spark': 'spl-arcane-bolt',
  'spl-ghost-lantern': 'spl-second-chance',
  'spl-inferno': 'spl-burning-ground',
  'spl-wall-of-flame': 'spl-burning-ground',
  'spl-oath-blade': 'spl-giants-bane',
  'spl-consecrate': 'spl-ward-circle',
  'spl-enfeeble': 'spl-weakness',
  'spl-flesh-altar': 'spl-blood-pact',
  'spl-dark-ritual': 'spl-blood-pact',
  'spl-meteor': 'spl-siege-fire',
  'spl-reliquary-blade': 'spl-giants-bane',
  'spl-oath-of-vengeance': 'spl-power-surge',
  'spl-death-wave': 'spl-soul-burn',
  'tok-skeleton': 'und-bone-soldier',
  'tok-ward': 'spl-aegis-ward',
};
