/** Character writing is separate from rules: changing a story never changes a match. */
export const CARD_LORE: Record<string, { title: string; quote: string; story: string }> = {
  'kng-paladin': { title: 'The last oath of spring', quote: 'A shield is a promise with a handle.', story: 'Captain Avel keeps a sprig from the orchard where she took her oath. The court has changed its banners three times since then. She has never changed the people she stands in front of.' },
  'und-vharos': { title: 'The king who kept watch', quote: 'Read their names. That is all I ever asked.', story: 'When the royal furnace demanded the forgotten, Vharos sewed their names into his cloak. He has stood between the fire and the graves for a century. The living remember a tyrant. The dead remember a door that never closed.' },
  'und-mira': { title: 'Keeper of the missing', quote: 'No one is gone while someone is looking.', story: 'Mira does not raise armies. She finds people who never made it home. Her ledger lists a thousand names, each crossed out only when a lantern reaches the right doorstep.' },
  'und-bone-soldier': { title: 'An unfinished watch', quote: 'Relief was due at dawn.', story: 'The uniform has rotted and the orders have faded. Still, every evening, the soldier faces the forest. The road behind him must remain safe. He remembers that much.' },
  'inf-infernal-lord': { title: 'The creditor of winter', quote: 'You asked for warmth. We agreed on a price.', story: 'He arrived during the longest winter, with enough fire for every hearth. The king signed. Spring returned. Only later did the census clerks discover that whole streets had vanished from their books.' },
  'inf-hellhound': { title: 'The furnace remembers', quote: 'It follows the warmth you leave behind.', story: 'Bred in the royal furnace, these hounds can track a promise long after its speaker has died. A cold lantern will hide you. A guilty heart will not.' },
  'kng-light-priest': { title: 'A small, stubborn light', quote: 'Keep one window lit.', story: 'When the ash began to fall, the temple shuttered its doors. One priest stayed outside with a kettle, clean bandages, and the sort of faith that does not need an audience.' },
};
