import type { CardDefinition } from '../types';

// Spells are faction-neutral - any deck can include any of them. Faction here is flavor only.
//
// Every Spell's target is automatic from the lane it's placed in (or global, for board-wide Spells
// that still drop into a Spell slot the same way). None of these ask the player to "choose" a target.
//
// ONE_TIME Spells resolve once here and go straight to the Graveyard, freeing their slot. CONTINUOUS
// Spells activate once and then stay in their slot; only an ability with a recurring trigger
// (ROUND_END, ON_ALLY_DEATH, ...) or the special CONTINUOUS trigger (a live, always-on modifier -
// see Battle Banner) does anything after that.

export const INSTANT_SPELL_CARDS: CardDefinition[] = [
  {
    id: 'spl-power-surge',
    name: 'Power Surge',
    shortName: 'Power Surge',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: '+3 Power this round',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: 3, duration: 'UNTIL_ROUND_END', target: 'ALLY_SAME_LANE' }],
        text: 'Your Hero in this lane gains +3 Power this round.',
      },
    ],
  },
  {
    id: 'spl-weakness',
    name: 'Weakness',
    shortName: 'Weakness',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Enemy -3 this round',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: -3, duration: 'UNTIL_ROUND_END', target: 'ENEMY_SAME_LANE' }],
        text: 'The enemy Hero in this lane loses 3 Power this round.',
      },
    ],
  },
  {
    id: 'spl-execute',
    name: 'Execute',
    shortName: 'Execute',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Destroy if 3 Power or less',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'DESTROY', target: 'ENEMY_SAME_LANE', maxPower: 3 }],
        text: 'Destroy the enemy Hero in this lane if it has 3 Power or less.',
      },
    ],
  },
  {
    id: 'spl-second-chance',
    name: 'Second Chance',
    shortName: 'Second Chance',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Return strongest ally',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'HIGHEST_POWER' }],
        text: 'Return the strongest Hero from your Graveyard to your hand.',
      },
    ],
  },
  {
    id: 'spl-raise-fallen',
    name: 'Raise Fallen',
    shortName: 'Raise Fallen',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Revive Undead w/ 3+ in Grave',
    abilities: [
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'GRAVEYARD_FACTION_COUNT_AT_LEAST', faction: 'undead', count: 3 }],
        actions: [{ type: 'REVIVE_TO_LANE', maxPower: Infinity, pick: 'LOWEST_POWER', faction: 'undead' }],
        text: 'If your Graveyard holds 3 or more Undead Heroes, revive the weakest one into this lane.',
      },
    ],
  },
  {
    id: 'spl-fireball',
    name: 'Fireball',
    shortName: 'Fireball',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Enemy -4; =1 w/ enemy Spell',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: -4, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }],
        text: 'The enemy Hero in this lane loses 4 Power.',
      },
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'ENEMY_LANE_HAS_SPELL' }],
        actions: [{ type: 'SET_POWER', value: 1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }],
        text: "If the enemy has a Continuous Spell active in this lane, that Hero's Power is set to 1 instead.",
      },
    ],
  },
  {
    id: 'spl-war-cry',
    name: 'War Cry',
    shortName: 'War Cry',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: '+2 allies; +1 w/ 2+ Kingdom',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'ALL_ALLIES' }],
        text: 'All allied Heroes gain +2 Power this round.',
      },
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'ALLY_FACTION_COUNT_AT_LEAST', faction: 'kingdom', count: 2 }],
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'UNTIL_ROUND_END', target: 'ALL_ALLIES' }],
        text: 'If you control 2 or more Kingdom Heroes, all allied Heroes gain an additional +1 Power this round.',
      },
    ],
  },
  {
    id: 'spl-death-wave',
    name: 'Death Wave',
    shortName: 'Death Wave',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'All enemies -2 this round',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'CHANGE_POWER', amount: -2, duration: 'UNTIL_ROUND_END', target: 'ALL_ENEMIES' }],
        text: 'All enemy Heroes lose 2 Power this round.',
      },
    ],
  },
  {
    id: 'spl-dispel',
    name: 'Dispel',
    shortName: 'Dispel',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Destroy enemy Spell',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'DESTROY_SPELL_ZONE', target: 'ENEMY_SAME_LANE' }],
        text: 'Destroy the enemy Continuous Spell in this lane.',
      },
    ],
  },
  {
    id: 'spl-soul-burn',
    name: 'Soul Burn',
    shortName: 'Soul Burn',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'epic',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Exile strongest enemy',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'EXILE_FROM_GRAVEYARD', pick: 'HIGHEST_POWER' }],
        text: "Exile the strongest Hero from the enemy's Graveyard.",
      },
    ],
  },
  // --- Expansion ----------------------------------------------------------------------------------------
  {
    id: 'spl-arcane-bolt',
    name: 'Arcane Bolt',
    shortName: 'Arcane Bolt',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Dmg 3; 5 after another Spell',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'PLAYER_DAMAGE', amount: 3 }],
        text: 'Deal 3 damage to the enemy player.',
      },
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'SPELLS_PLAYED_THIS_ROUND_AT_LEAST', count: 1 }],
        actions: [{ type: 'PLAYER_DAMAGE', amount: 2 }],
        text: 'If you already played a Spell this round, deal 2 more.',
      },
    ],
  },
  {
    id: 'spl-aegis-ward',
    name: 'Aegis Ward',
    shortName: 'Aegis Ward',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Ignore next damage this rd',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'PREVENT_NEXT_DAMAGE', count: 1 }],
        text: 'The next damage your player would take this round is prevented.',
      },
    ],
  },
  {
    id: 'spl-ward-circle',
    name: 'Ward Circle',
    shortName: 'Ward Circle',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Summon 2 Ward tokens',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'SUMMON_TOKEN', tokenId: 'tok-ward', count: 2 }],
        text: 'Summon a Ward token in each of up to 2 empty Hero lanes.',
      },
    ],
  },
  {
    id: 'spl-stasis-field',
    name: 'Stasis Field',
    shortName: 'Stasis Field',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'No combat in this lane',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'STALL_COMBAT', target: 'ENEMY_SAME_LANE' }],
        text: 'The enemy Hero in this lane cannot fight this round: no combat happens in this lane.',
      },
    ],
  },
  {
    id: 'spl-hush',
    name: 'Hush',
    shortName: 'Hush',
    faction: 'undead',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'common',
    cost: 1,
    tags: ['Spell'],
    boardText: 'Silence enemy this round',
    abilities: [
      {
        trigger: 'ON_PLAY',
        actions: [{ type: 'SILENCE', target: 'ENEMY_SAME_LANE' }],
        text: 'Silence the enemy Hero in this lane for the rest of the round.',
      },
    ],
  },
  {
    id: 'spl-giants-bane',
    name: "Giant's Bane",
    shortName: "Giant's Bane",
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Destroy if outnumbered',
    abilities: [
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'ENEMY_HERO_COUNT_HIGHER' }],
        actions: [{ type: 'DESTROY', target: 'ENEMY_SAME_LANE' }],
        text: 'If the enemy controls more Heroes than you, destroy the enemy Hero in this lane.',
      },
    ],
  },
  {
    id: 'spl-blood-pact',
    name: 'Blood Pact',
    shortName: 'Blood Pact',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'ONE_TIME',
    role: 'Spell',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Sac ally: kill enemy (<=6)',
    abilities: [
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'SELF_LANE_OCCUPIED' }, { type: 'LANE_OCCUPIED_ENEMY_SIDE' }],
        actions: [
          { type: 'DESTROY', target: 'ALLY_SAME_LANE' },
          { type: 'DESTROY', target: 'ENEMY_SAME_LANE', maxPower: 6 },
        ],
        text: 'Destroy your Hero in this lane, then destroy the enemy Hero in this lane if it has 6 Power or less.',
      },
    ],
  },
];

export const PERSISTENT_SPELL_CARDS: CardDefinition[] = [
  {
    id: 'spl-battle-banner',
    name: 'Battle Banner',
    shortName: 'Battle Banner',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: '+2 Power while active',
    abilities: [
      {
        // A live overlay, not a re-applied buff: it adds to effective Power everywhere that's read
        // (Combat, direct damage, display) and simply stops contributing the instant this Spell is
        // gone - it never permanently mutates the Hero it's boosting.
        trigger: 'CONTINUOUS',
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }],
        text: 'Your Hero in this lane has +2 Power.',
      },
    ],
  },
  {
    id: 'spl-burning-ground',
    name: 'Burning Ground',
    shortName: 'Burning Grnd',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Round End: Enemy -1',
    abilities: [
      {
        trigger: 'ROUND_END',
        actions: [{ type: 'CHANGE_POWER', amount: -1, duration: 'PERMANENT', target: 'ENEMY_SAME_LANE' }],
        text: 'At the end of each round, the enemy Hero in this lane loses 1 Power.',
      },
    ],
  },
  {
    id: 'spl-growth-totem',
    name: 'Growth Totem',
    shortName: 'Growth Totem',
    faction: 'wildborn',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Round End: Ally +1',
    abilities: [
      {
        trigger: 'ROUND_END',
        conditions: [{ type: 'SELF_LANE_OCCUPIED' }],
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }],
        text: 'Your Hero in this lane gains +1 Power at the end of each round.',
      },
    ],
  },
  {
    id: 'spl-fortify',
    name: 'Fortify',
    shortName: 'Fortify',
    faction: 'kingdom',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'epic',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Round End: Ally +1',
    abilities: [
      {
        trigger: 'ROUND_END',
        conditions: [{ type: 'SELF_LANE_OCCUPIED' }],
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }],
        text: 'Your Hero in this lane gains +1 Power at the end of each round.',
      },
    ],
  },
  {
    id: 'spl-cursed-ground',
    name: 'Cursed Ground',
    shortName: 'Cursed Ground',
    faction: 'undead',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Enemy dies: Ally +1',
    abilities: [
      {
        trigger: 'ON_ENEMY_DEATH',
        conditions: [{ type: 'SELF_LANE_OCCUPIED' }],
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'ALLY_SAME_LANE' }],
        text: 'Whenever an enemy Hero dies, your Hero in this lane gains +1 Power.',
      },
    ],
  },
  {
    id: 'spl-siege-fire',
    name: 'Siege Fire',
    shortName: 'Siege Fire',
    faction: 'infernal',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'rare',
    cost: 2,
    tags: ['Spell'],
    boardText: 'Round End: 1 dmg if empty',
    abilities: [
      {
        trigger: 'ROUND_END',
        conditions: [{ type: 'LANE_EMPTY_ENEMY_SIDE' }],
        actions: [{ type: 'PLAYER_DAMAGE', amount: 1 }],
        text: "At the end of each round, if the enemy's Hero zone in this lane is empty, deal 1 damage to the enemy player.",
      },
    ],
  },
  {
    id: 'spl-grave-totem',
    name: 'Grave Totem',
    shortName: 'Grave Totem',
    faction: 'undead',
    type: 'spell',
    spellKind: 'CONTINUOUS',
    role: 'Aura',
    rarity: 'epic',
    cost: 2,
    tags: ['Spell'],
    boardText: '1st death/round: Return',
    abilities: [
      {
        trigger: 'ON_ALLY_DEATH',
        conditions: [{ type: 'DEATH_IN_SELF_LANE' }, { type: 'SPELL_ZONE_NOT_USED_THIS_ROUND' }],
        actions: [{ type: 'RETURN_DEATH_SOURCE_TO_HAND' }],
        text: 'The first allied Hero that dies in this lane each round returns to your hand.',
      },
    ],
  },
];
