import type { CardDefinition } from '../types';

// Undead - skeletons, wraiths and necromancers. Death triggers, Graveyard, revival, sacrifice.

export const UNDEAD_CARDS: CardDefinition[] = [
  {
    id: 'und-bone-soldier',
    name: 'Bone Soldier',
    shortName: 'Bone Soldier',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Skeleton'],
    boardText: 'Death:Return; +1/Grave card',
    abilities: [
      {
        trigger: 'ON_DEATH',
        actions: [{ type: 'RETURN_TO_DECK' }],
        text: 'On Death: Return this card to your Deck.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        actions: [{ type: 'CHANGE_POWER_BY_COUNT', basis: 'GRAVEYARD_COUNT', perCount: 1, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: gain +1 Power this round for each card in your Graveyard.',
      },
    ],
  },
  {
    id: 'und-dark-priest',
    name: 'Dark Priest',
    shortName: 'Dark Priest',
    faction: 'undead',
    type: 'hero',
    role: 'Support',
    rarity: 'rare',
    cost: 2,
    power: 3,
    tags: ['Undead'],
    boardText: 'Ally dies:+1; +2 w/3+ Grave',
    abilities: [
      {
        trigger: 'ON_ALLY_DEATH',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }],
        text: 'When an ally dies, gain +1 Power.',
      },
      {
        trigger: 'BEFORE_COMBAT',
        conditions: [{ type: 'GRAVEYARD_COUNT_AT_LEAST', count: 3 }],
        actions: [{ type: 'CHANGE_POWER', amount: 2, duration: 'UNTIL_ROUND_END', target: 'SELF' }],
        text: 'Before Combat: if your Graveyard holds 3 or more cards, gain +2 Power this round.',
      },
    ],
  },
  {
    id: 'und-mira',
    name: 'Mira',
    shortName: 'Mira',
    faction: 'undead',
    type: 'hero',
    role: 'Necromancer',
    rarity: 'epic',
    cost: 3,
    power: 4,
    tags: ['Undead'],
    boardText: 'Return Undead; Immune w/3+Grv',
    abilities: [
      {
        trigger: 'ON_PLAY',
        conditions: [{ type: 'HAND_SIZE_AT_MOST', count: 4 }],
        actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'LOWEST_POWER', faction: 'undead' }],
        text: 'On Play: if your hand holds 4 or fewer cards, return an Undead Hero from your Graveyard to your hand.',
      },
      {
        trigger: 'PASSIVE',
        conditions: [{ type: 'GRAVEYARD_FACTION_COUNT_AT_LEAST', faction: 'undead', count: 3 }],
        actions: [{ type: 'GRANT_IMMUNITY', immunity: 'HERO_EFFECT', target: 'SELF' }],
        text: 'While your Graveyard holds 3 or more Undead Heroes, this Hero is immune to hostile Hero abilities.',
      },
    ],
  },
  {
    id: 'und-cursed-warrior',
    name: 'Cursed Warrior',
    shortName: 'Cursed Warrior',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'common',
    cost: 1,
    power: 4,
    tags: ['Undead'],
    boardText: 'On Death: Return to hand',
    abilities: [
      {
        trigger: 'ON_DEATH',
        actions: [{ type: 'RETURN_DEATH_SOURCE_TO_HAND' }],
        text: 'On Death: Return this card to your hand.',
      },
    ],
  },
  {
    id: 'und-grave-knight',
    name: 'Grave Knight',
    shortName: 'Grave Knight',
    faction: 'undead',
    type: 'hero',
    role: 'Fighter',
    rarity: 'rare',
    cost: 2,
    power: 4,
    tags: ['Undead', 'Knight'],
    boardText: 'Enemy dies:+1; 1st/rnd: Heal2',
    abilities: [
      {
        trigger: 'ON_ENEMY_DEATH',
        actions: [{ type: 'CHANGE_POWER', amount: 1, duration: 'PERMANENT', target: 'SELF' }],
        text: 'When an enemy Hero dies, gain +1 Power.',
      },
      {
        trigger: 'ON_ENEMY_DEATH',
        oncePerRound: true,
        actions: [{ type: 'PLAYER_HEAL', amount: 2 }],
        text: 'The first time an enemy Hero dies each round, heal your player for 2.',
      },
    ],
  },
  {
    id: 'und-vharos',
    name: 'Vharos',
    shortName: 'Vharos',
    faction: 'undead',
    type: 'hero',
    role: 'Undead',
    rarity: 'legendary',
    cost: 4,
    power: 7,
    tags: ['Undead'],
    boardText: 'Death: Revive4; Return random',
    abilities: [
      {
        trigger: 'ON_DEATH',
        actions: [{ type: 'REVIVE_SELF', power: 4 }],
        text: 'On Death: Revive this Hero into the same lane with 4 Power.',
      },
      {
        trigger: 'ON_DEATH',
        actions: [{ type: 'RETURN_TO_HAND', maxPower: Infinity, pick: 'RANDOM', faction: 'undead' }],
        text: 'On Death: Also return a random Undead Hero from your Graveyard to your hand.',
      },
    ],
  },
];
